### ISSUE TITLE
Test Write/Update Incident-Based

### ISSUE THREAD

**Issue by LeonardKoll** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#459]
**Beschreibung**

- [x] Einfühung eines POST-Endpoints, welcher Test-Incidents konsumiert und die entsprechenden Datenbankinteraktionen (Write/Update) ausführt

- [x] Das Frontend legt Tests an und Testresultate ab, indem es auf diese POST-Endpoints zurückgreift.

- [x] Da die Darstellung von Testzuständen bereits auf Incidents basiert sollen alle weiteren Verwendungen von LabTest entfernt werden.

- [x] Redundanzen aus der Klasse Patient entfernen (PatientEvent Mapping)

**Roadmap**
https://docs.google.com/document/d/1cbrvP_LKiFH2Ca1kU5zK3Iqb1ji5pSYMae_AEdaXX6E/edit

**Comment by Jochen-Sch** [comment]
Zum Thema mögliche Ergebnisse der Tests (Test Typ PCR):
Im UI sollten TEST_POSITIVE, TEST_NEGATIVE, TEST_INVALID verfügbar sein sowie die möglichkeit das Ergebnis auf 'nicht erfasst'/'nicht bekannt' zu setzen (z.B. sofern die Ergebnisse als Radio Buttons dargestellt sind. Dies ermöglichst das 'zurücksetzen' des erfassten Ergebnisses falls aus Versehen ein Wert ausgewählt wurde obwohl noch gar kein Ergebnis vorliegt und eigentlich nur andere Daten des Tests aktualisiert worden sind. (Hänbgt vom tatsächlichen Screen ab - d.h. sofern es einen Screen nur für Ergebniserfassung gilt macht das nicht-erfassen natürlich keinen Sinn).
Im Backend sollte sofern ein test kein Ergebnis hat der Status 'TEST_SUBMITTED' gesetzt werden. Dies wäre der Fall sobald ein Test initial erfasst wird ohne dass bereits ein Ergebnis vorliegt (z.B. beim Arzt, Klinik, ...)
