### ISSUE TITLE
Quarantine Write/Update Incident-Based

### ISSUE THREAD

**Issue by LeonardKoll** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#460]
**Beschreibung**

- [x] Einfühung eines POST-Endpoints, welcher QuarantineIncidents konsumiert und die entsprechenden Datenbankinteraktionen (Write/Update) ausführt

- [x] Das Frontend merkt Quarantäne vor und sendet Patienten in Quarantäne, indem es auf entsprechende POST-Endpoints zurückgreift

- [x] Redundanzen aus der Klasse Patient entfernen (quarantineUntil)

- [x] Entsprechende Frotnendimplikationen für die Patientenübersicht beachten (Filtering)

**Roadmap**
https://docs.google.com/document/d/1cbrvP_LKiFH2Ca1kU5zK3Iqb1ji5pSYMae_AEdaXX6E/edit

**Comment by btobi** [comment]
Das Filtern nach Quarantänestatus in der Patientensuche hat bislang nicht funktioniert. Daher ändert sich auch mit der Umstellung auf Incidents nichts. Das Suchfeld wurde auskommentiert, sodass es für die Suche nicht mehr zur Verfügung steht.
