### ISSUE TITLE
Hospitalisierung Write/Update Incident-Based

### ISSUE THREAD

**Issue by LeonardKoll** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#461]
**Beschreibung**

- [ ] Einfühung eines POST-Endpoints, welcher HospitalizationIncidents konsumiert und die entsprechenden Datenbankinteraktionen (Write/Update) ausführt

- [ ] Das Frontend vermerkt und beendet Hospitalisierungen, indem es entspechende Write / Updates mit den POST-Endpoint durchführt.

- [ ] Redundanzen aus der Klasse Patient entfernen (Hospitalisierungs-Datum und onIntensiveCare)

- [ ] Frontend-Implikationen beachten: Hospitalisierung ist, wie Quarantäne, nicht mehr ein Merkmal des Patienten sondern ein Prozess mit einem Anfang (Hospitalisiert) und einem Ende (Hospitalisierung aufgehoben)

- [ ] Beim Erstellen eines Patienten: Wenn Hospitalisierung mit Datum mitgeschickt wird, soll automatisch im Backend ein entsprechender Incident angelegt werden.

**Roadmap**
https://docs.google.com/document/d/1cbrvP_LKiFH2Ca1kU5zK3Iqb1ji5pSYMae_AEdaXX6E/edit

**Comment by LeonardKoll** [comment]
Ich habe den Bug über den wir uns unterhalten hatten hier vermerkt: #468 
Hatte das Problem bei der Umstellung der Falldaten auf Incidents leider nicht mehr behoben :/
