### ISSUE TITLE
Incident based frontend - finishing steps

### ISSUE THREAD

**Issue by LeonardKoll** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#466]
**Beschreibung**

- [ ] Entfernen von PatientEvent

- [ ] Der Patienten-Status (Entität Patient) wird zunächst abgeschafft da es keinen "Gesamtstatus" mehr gibt. Ein solcher kann in einem nachgelagerten Schritt wieder eingeführt werden - wie das geschieht wird aber ein eigenes Issue.

- [ ] Case Support (caseID) kann lt aktuellem Feedback vom GA entfernt werden. Siehe https://docs.google.com/document/d/1wPAhve-97etTnH6yeHUUfVAJAzr9oeLOc78iDPT_dpQ/edit "Fälle werden unabhängig von der Historie der Person betrachtet. D.h. unser Patient ist tatsächlich der Fall. Ein Mapping bzw. eine Erkennung dass eine Person erneut erkrankt ist ist nicht notwendig."

**Roadmap**
https://docs.google.com/document/d/1cbrvP_LKiFH2Ca1kU5zK3Iqb1ji5pSYMae_AEdaXX6E/edit
